# creating Retina volumes:
docker volume create --name=retina-app-logo
docker volume create --name=retina-app-logs
docker volume create --name=retina-app-tmp
docker volume create --name=retina-app-repository-search
docker volume create --name=retina-app-repository-logs
docker volume create --name=retina-app-repository-update
docker volume create --name=retina-app-repository-access
docker volume create --name=retina-app-repository-svn
docker volume create --name=retina-app-repository-git
docker volume create --name=retina-app-repository-hg
docker volume create --name=retina-app-repository-docs
docker volume create --name=retina-app-repository-wiki
docker volume create --name=retina-db-data