# Copyright by Intland Software, https://www.intland.com
#
# All rights reserved.
#
# Please note that if you change this docker file, we do not take any responsibility and we are not liable for
# any damage caused through use of this image, be it indirect, special, incidental
# or consequential damages (including but not limited to damages for loss of business, loss of profits, interruption or the like).

version: '2.1'

services:
  retina-db:
    image: intland/mysql:5.7.21
    environment:
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
      - MYSQL_DATABASE=retina
      - MYSQL_MAX_ALLOWED_PACKET=1024M
      - MYSQL_INNODB_BUFFER_POOL_SIZE=1G
      - MYSQL_INNODB_LOG_FILE_SIZE=256M
      - MYSQL_INNODB_LOG_BUFFER_SIZE=256M
    volumes:
      - retina-db-data:/var/lib/mysql/data

  retina-app:
    image: intland/retina:3.1
    ports:
      - 8888:8080
    environment:
      - TZ=Europe/Berlin
      - WAIT_HOSTS=container-mysql:3306
      - WAIT_HOSTS_TIMEOUT=120
      - CB_REDIRECT_TO=/retina
      - CB_CONTEXT_PATH=cb
      - CB_database_JDBC_Username=user
      - CB_database_JDBC_Password=pass
      - CB_database_JDBC_Driver=com.mysql.jdbc.Driver
      - CB_database_JDBC_ConnectionURL=jdbc:mysql://container-mysql:3306/retina?autoReconnect=true&zeroDateTimeBehavior=convertToNull&emulateLocators=true&characterEncoding=UTF-8&useSSL=false      - CB_database_JDBC_Timeout=120
      - CB_MAC_ADDRESS=84:EF:18:D2:21:8F
      - CB_LICENSE=<license code="14317CFDFDE9FF50" companyName="B-H-C (Partner Licenses)" expire="Jun-30-2021" generatedForRelease="10.0.0 - ... " generationTime="Nov-11-2020 14:04" generatorRelease="10.1" generatorUser="daniel.jaikumar@intland.com" hostid="LIN-84:EF:18:D2:21:8F">
          <product type="ALM +Escalation +Service Desk +Doors bridge +Jira integration +Branching">
              <user kind="named" licenses="3" type="user"/>
          </product>
        </license>
      - CB_mail_host=smtp.plm4ee.de
      - CB_mail_user=retina@b-h-c.de
      - CB_mail_password=spBsg63_qbdm
      - CB_mail_ssl=false
      - CB_mail_smtpPort=25
      - CB_mail_serverScheme=http
      - CB_mail_from=retina@b-h-c.de
      - CB_mail_localname=localhost
      - CB_mail_serverPort=8080

    volumes:
      - .\retina-data\retina-app-repository:/home/appuser/codebeamer/repository
      - .\retina-data\retina-app-logs:/home/appuser/codebeamer/logs
      - .\retina-data\retina-app-logo:/home/appuser/retina/tomcat/webapps/ROOT/config/logo
      - .\retina-data\retina-app-logs:/home/appuser/retina/logs
      - .\retina-data\retina-app-tmp:/home/appuser/retina/tomcat/tmp
      - .\retina-data\retina-app-repository-update:/home/appuser/retina/update
      - .\retina-data\retina-app-repository-access:/home/appuser/retina/repository/access
      - .\retina-data\retina-app-repository-svn:/home/appuser/retina/repository/svn
      - .\retina-data\retina-app-repository-git:/home/appuser/retina/repository/git
      - .\retina-data\retina-app-repository-hg:/home/appuser/retina/repository/hg
      - .\retina-data\retina-app-repository-docs:/home/appuser/retina/repository/docs
      - .\retina-data\retina-app-repository-wiki:/home/appuser/retina/repository/wiki
      - .\retina-data\retina-app-repository-search:/home/appuser/retina/repository/search

    links:
      - retina-db:container-mysql

  retina-httpd:
    image: intland/httpd:1.2
    ports:
      - 80:8887
      - 443:8888
    environment:
      - WAIT_HOSTS=retina-app:8080
      - WAIT_HOSTS_TIMEOUT=180
    volumes:
      - .\retina-data\retina-app\retina.example.net.cert:/home/appuser/certificates/pem/certificate-file.pem
      - .\retina-data\retina-app\retina.example.net.key:/home/appuser/certificates/pem/certificate-key-file.pem

    links:
        - retina-app:codebeamer-app
volumes:
  retina-db-data:
    name: retina-db-data
    external: true
  retina-app-repository-docs:
    name: retina-app-repository-docs
    external: true
  retina-app-repository-logs:
    name: retina-app-repository-logs
    external: true
  retina-app-repository-update:
    name: retina-app-repository-update
    external: true
  retina-app-repository-access:
    name: retina-app-repository-access
    external: true
  retina-app-repository-svn:
    name: retina-app-repository-svn
    external: true
  retina-app-repository-git:
    name: retina-app-repository-git
    external: true
  retina-app-repository-hg:
    name: retina-app-repository-hg
    external: true
  retina-app-repository-docs:
    name: retina-app-repository-docs
    external: true
  retina-app-repository-wiki:
    name: retina-app-repository-wiki
    external: true
  retina-app-repository-search:
    name: retina-app-repository-search
    external: true
  retina-db-data:
    name: retina-db-data
    external: true
  retina-app-logo:
    name: retina-app-logo
    external: true
  retina-app-logs:
    name: retina-app-logs
    external: true
  retina-app-tmp:
    name: retina-app-tmp
    external: true
